defaults:
  - schema
  - _self_

# Dyck 100M: 50M paren pre-train -> 2 epochs CHILDES -> <=50M CHILDES tokens
name: dyck_100m_childes
data_path: ./data/base/nt_dataset
model_save_path: ./models/pythia/dyck_100m_childes_model
model_load_path: ./models/pythia/dyck_100m_model
num_train_epochs: 2
train_truncation: 48828
lock_epochs: true
token_limit: 50000000
