defaults:
  - schema
  - _self_

# POS pre-training: 5M POS -> random 5M CHILDES (train_truncation ~= 9765 examples)
name: pos_5m_childes
data_path: ./data/base/nt_dataset
model_save_path: ./models/pythia/pos_5m_childes_model
model_load_path: ./models/pythia/pos-model
num_train_epochs: 1
train_truncation: 9765  # 9765 x 512 ~= 5M tokens
